- name: Build Project (Unsigned)
        run: |
          xcodebuild -workspace Brokenithm-iOS.xcworkspace \
                     -scheme Brokenithm-iOS \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath build \
                     IPHONEOS_DEPLOYMENT_TARGET=12.0 \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     AD_HOC_CODE_SIGNING_ALLOWED=YES \
                     ENABLE_BITCODE=NO \
                     COMPILER_INDEX_STORE_ENABLE=NO \
                     clean build